# Assignment 3

### Task 1.1

In [9]:
def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError as ze:
    print("Division by ZERO error!!")
except:
    print("Any other exception")

Division by ZERO error!!


### Task 1.2

In [5]:
subject = ["Americans", "Indians"]
verb = ["Play", "watch"]
obj = ["Baseball","cricket"]

In [7]:
sentence = [(sub + " " + vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sent in sentence:
    print (sent)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


### Task 2.1

In [20]:
def vander(x, N, order):
    X = x.size
    result_array = np.empty((N + 1, X), dtype = int)
    
    if order.upper() == "TRUE":
        for i in range(N + 1):
            power_vector = np.array(np.power(x, i))
            result_array[i] = power_vector
    else:
        for i in range(N-1, -1, -1):
            power_vector = np.array(np.power(x, i))
            result_array[(N-1)-i] = power_vector
    return result_array

In [23]:
import numpy as np

N = int(input('Enter the value of N power :'))

print('Enter comma separated list of elements eg. 1,2,3 :')
input_vector = input()
input_list = list(map(int, input_vector.split(',')))
x = np.array(input_list)
print('Input vector is :')
print(x)

order = input("Enter 'True' for increasing order of powers else enter 'False' :")

result_array = vander(x,N,order)
print('The final matrix is :')
print(result_array.T)

Enter the value of N power :3
Enter comma separated list of elements eg. 1,2,3 :
1, 2, 3, 4
Input vector is :
[1 2 3 4]
Enter 'True' for increasing order of powers else enter 'False' :False
The final matrix is :
[[ 1  1  1  1]
 [ 4  2  1  8]
 [ 9  3  1 27]
 [16  4  1 64]]
